### ISSUE TITLE
Copyright notice for AndroidCommons library

### ISSUE THREAD

**Issue by flobetz** [alexvasilkov/AndroidCommons#2]
Hey Alex,
we are using your AndroidCommons library within our Android App and we have to list your library within our FOSS components. Therefore we need a Copyright notice which is, unfortunately, not available in this repo. 
Can you please provide this oneliner? 
Greetings
Flo

**Comment by alexvasilkov** [comment]
I'm not requiring a copyright notice for this library, but if you need you can use the next one:

"Copyright 2017 Alex Vasilkov".

+ common Apache 2.0 license template.

**Comment by flobetz** [comment]
Awesome, that's enough for us.
Thank you :)
